# Generated by Django 4.2.13 on 2024-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='mobile',
            field=models.IntegerField(default=9345681239, max_length=10),
            preserve_default=False,
        ),
    ]
