# Generated by Django 4.2.13 on 2024-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentify_app', '0002_house_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
